---
title: "main"
output: html_document
date: "2023-08-04"
---

#Today's Link: https://github.com/rfordatascience/tidytuesday/blob/master/data/2023/2023-07-11/readme.md

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
suppressMessages(library(tidyverse))
suppressMessages(library(skimr))
suppressMessages(library(plotly))
suppressMessages(library(tidymodels))
```

```{r EDA}
#Load in the data
global_temps <-
  readr::read_csv(
    'https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2023/2023-07-11/global_temps.csv'
  )

#nh_temps <-
#  readr::read_csv(
#    'https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2023/2023-07-11/nh_temps.csv'
# )

#sh_temps <-
#  readr::read_csv(
#    'https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2023/2023-07-11/sh_temps.csv'
#  )

#zonann_temps <-
#  readr::read_csv(
#    'https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2023/2023-07-11/zonann_temps.csv'
#  )

#I think we are just going to use the global_temps dataframe

skim(global_temps)
#skim(nh_temps)
#skim(sh_temps)
#skim(zonann_temps)
```

```{r EDA}
#Lets split the data into two sets, one for month and the other for seasonal, so we can compare the two 
Monthly_plot_data <- global_temps %>% 
  select(-c(14:19)) %>%
  drop_na() %>%
  pivot_longer(2:13, names_to = "Month", values_to = "TempChange")

Seasonal_plot_data <- global_temps %>% 
  select(-c(2:13)) %>%
  drop_na() %>%
  pivot_longer(2:7, names_to = "Season", values_to = "TempChange")
```

```{r EDA}
#Lets take a look at the mean temperature change
#The monthly and seasonal data tell significantly less concerning stories than the yearly data
G1 <- Monthly_plot_data %>% 
  select(-c(Year)) %>%
  group_by(Month) %>%
  summarise(mean = mean(TempChange)) %>%
  ggplot(mapping = aes(x = Month, y = mean, color = mean)) +
  theme(legend.position = "none") +
  scale_color_gradient(low = 'yellow', high = 'red') +
  geom_point(alpha = 0.7) 

G2 <- Seasonal_plot_data %>% 
  select(-c(Year)) %>%
  group_by(Season) %>%
  summarise(mean = mean(TempChange)) %>%
  ggplot(mapping = aes(x = Season, y = mean, color = mean)) +
  theme(legend.position = "none") +
  scale_color_gradient(low = 'yellow', high = 'red') +
  geom_point(alpha = 0.7) 

G3 <- Monthly_plot_data %>% 
  select(-c(Month)) %>%
  group_by(Year) %>%
  summarise(mean = mean(TempChange)) %>%
  ggplot(mapping = aes(x = Year, y = mean, color = mean)) +
  theme(legend.position = "none") +
  scale_color_gradient(low = 'yellow', high = 'red') +
  geom_point(alpha = 0.7) 

subplot(G1, G2, G3, margin = 0.1, nrows = 2) 
```

```{r EDA}
#Lets check out what happens to the monthly temperatures over the years
G4 <- Monthly_plot_data %>%
  plot_ly(x = ~ Month, y = ~ TempChange) %>%
  add_markers(data = Monthly_plot_data,
              color = ~ TempChange,
              size = ~ TempChange,
              frame = ~ Year,
              colors = "YlOrRd") %>%
  hide_legend() %>%
  animation_opts(transition = 0, redraw = FALSE)

G4
```



