---
title: "main"
output: html_document
date: "2023-06-19"
---

# Today's Link: https://github.com/rfordatascience/tidytuesday/tree/master/data/2023/2023-01-31

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
suppressMessages(library(tidyverse))
suppressMessages(library(tidymodels))
suppressMessages(library(gganimate))
suppressMessages(library(leaflet))
```

```{r EDA}
# Load in the data

cats_uk <- readr::read_csv(
  'https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2023/2023-01-31/cats_uk.csv'
)

cats_uk_reference <- readr::read_csv(
  'https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2023/2023-01-31/cats_uk_reference.csv'
)

view(cats_uk)
view(cats_uk_reference)

# I also want a year column to try and make an animation based on month
Catsdf <-
  merge(x = cats_uk, y = cats_uk_reference) %>% mutate(Month = lubridate::month(timestamp))

view(Catsdf)

```

```{r EDA}
Catsdf %>%
  group_by(animal_id) %>%
  summarize(count = n()) %>%
  arrange(desc(count))

Catsdf %>%
  select(tag_id) %>%
  summarize(name = unique(tag_id)) %>%
  arrange(name)

# Lets check out the movements of an indvidual cat later on
Abba <- Catsdf %>%
  filter(tag_id == "Abba-Tag") %>%
  mutate(start = min(timestamp)) %>%
  mutate(time_out = (lubridate::minute(timestamp) - lubridate::minute(start)) /
           60)
```

```{r EDA}
#max(Catsdf$location_lat,na.rm=TRUE)
#max(Catsdf$location_long,na.rm=TRUE)
#min(Catsdf$location_lat,na.rm=TRUE)
#min(Catsdf$location_long,na.rm=TRUE)

# There is a lot of data packed in close together
world <- map_data("world")

ggplot() +
  geom_map(
    data = world,
    map = world,
    aes(long, lat, map_id = region),
    color = "black",
    fill = "lightgray"
  )  +
  xlab("location_long") + ylab("location_lat") +
  coord_sf(xlim = c(-4.208613, -5.758853),
           ylim = c(50.88223, 50.10353)) +
  geom_point(
    data = Catsdf,
    aes(location_long, location_lat, color = animal_id),
    alpha = 0.8,
    show.legend = FALSE
  )

# Zoomed in version to show just how much data is packed in there
ggplot() +
  geom_map(
    data = world,
    map = world,
    aes(long, lat, map_id = region),
    color = "black",
    fill = "lightgray"
  )  +
  xlab("location_long") + ylab("location_lat") +
  coord_sf(xlim = c(-4.9240, -4.9200),
           ylim = c(50.5065, 50.509)) +
  geom_point(
    data = Catsdf,
    aes(location_long, location_lat, color = animal_id),
    alpha = 0.8,
    show.legend = FALSE
  )
```



```{r EDA}
# Take a look at where Abba goes

cat_map <- leaflet(Abba) %>%
  addTiles() %>%
  addPolylines(
    lng = ~ location_long,
    lat = ~ location_lat,
    opacity = 0.5
  ) %>%
  addCircles(lng = ~ location_long, lat = ~ location_lat)

cat_map
```

```{r EDA}
ggplot(Catsdf,
       aes(
         x = age_years,
         y = prey_p_month,
         size = n_cats,
         colour = animal_sex
       )) +
  geom_point(show.legend = TRUE, alpha = 0.7) +
  scale_color_viridis_d() +
  transition_time(Month) +
  labs(title = 'Month: {frame_time}')
```
