---
title: "main"
output: html_document
date: "2023-07-20"
---

# Today's Link: https://github.com/rfordatascience/tidytuesday/blob/master/data/2023/2023-04-18/readme.md

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
suppressMessages(library(tidyverse))
suppressMessages(library(skimr))
suppressMessages(library(plotly))
suppressMessages(library(gganimate))
suppressMessages(library(tidymodels))
```

```{r EDA}
founder_crops <-
  readr::read_csv(
    'https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2023/2023-04-18/founder_crops.csv'
  )

skim(founder_crops)
```

```{r EDA}
# lets look at the median proportion of founder crops (we use median since there are some impactful outliers)

v <- founder_crops %>%
  filter(!is.na(category)) %>%
  group_by(category, site_name) %>%
  summarize(prop = median(prop)) %>%
  plot_ly(
    y = ~prop,
    type = 'violin',
    box = list(
      visible = T
    ),
    meanline = list(
      visible = T
    ),
    x = ~category,
    color = ~category
  ) 
v
```

```{r EDA}
# Lets make use of the latitude and longitudes to make a map

world <- map_data("world")

g <- ggplot() +
  geom_map(
    data = world,
    map = world,
    mapping = aes(x = long, y = lat, map_id = region),
    color = "black",
    fill = "lightgrey"
  ) +
  geom_point(data = founder_crops,
             mapping = aes(x = longitude, y = latitude, color = family)) +
  coord_sf(xlim = c(27,50),  ylim = c(28, 43)) +
  theme(legend.position = "none") +
  xlab("Longitude") + 
  ylab("Latitude") +
  transition_reveal(age_start) +
  labs(title = 'Year: {frame_along}')

animate(g, fps = 5)
```

```{r Modeling}
# lets see if we can build a decent model to predict category (were just gonna do a simple model)
set.seed(0)

founder_crops_spl <- founder_crops %>%
  filter(!is.na(category)) %>%
  initial_split()

train <- training(founder_crops_spl)
test <- testing(founder_crops_spl)

train_fold5 <- train %>%
  vfold_cv(5)

#If we just use family we can get a really good roc_auc score, but I want to see if we can use other predictors
#If we get rid of all the steps and just use family it comes out to about ~0.9

tune <- recipe(category ~  prop + n + age_end, train) %>%
  step_impute_median(all_numeric_predictors()) %>%
  step_ns(age_end, deg_free = tune()) %>%
  step_other(all_nominal_predictors(), threshold = 0.1) %>%
  workflow(multinom_reg()) %>%
  tune_grid(
    train_fold5,
    metrics = metric_set(roc_auc),
    grid = crossing(
      deg_free = seq(1, 7, 2)
    )
  )

tune %>%
  autoplot()
```
```{r Modeling}
#Lets try one more model for fun

set.seed(0)

Forest <- recipe(category ~  family + taxon, train) %>%
  step_other(all_nominal_predictors(), threshold = 0.1) %>%
  workflow(rand_forest(mode = "classification")) %>%
  fit_resamples(train_fold5,
                metrics = metric_set(roc_auc)) %>%
  collect_metrics()

Forest
```

