---
title: "main"
output: html_document
date: "2023-07-03"
---

# Today's Link: https://github.com/rfordatascience/tidytuesday/tree/master/data/2023/2023-02-21

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
suppressMessages(library(tidyverse))
suppressMessages(library(stm))
suppressMessages(library(tidytext))
suppressMessages(library(tidylo))
```

```{r EDA}
# Load in the Data
bob_ross <- read_csv(
  "https://raw.githubusercontent.com/jwilber/Bob_Ross_Paintings/master/data/bob_ross_paintings.csv",
) 

view(bob_ross)
```
```{r EDA}
# We are breaking up the title into individual words
BrokenTitle <- bob_ross %>%
  select(painting_title) %>%
  mutate(NewTitle = tolower(painting_title)) %>%
  mutate(NewTitle = strsplit(NewTitle, split = " ")) %>%
  unnest(NewTitle)

# removing words we don't want to use
stopWords <-
  c("a", "in", "of", "at", "the", "by", "an", "on", "to", "c", "o", "and")
BrokenTitle <- subset(BrokenTitle, !(NewTitle %in% stopWords)) 

```

```{r EDA}
# Now we clean up the colors and color_hex
remove <- c("\\[", "\\]", "'", "\\\\n", "\\\\r")

colorSelect <- bob_ross %>%
  select(colors, color_hex) %>%
  mutate(
    color_hex = str_remove_all(color_hex, paste(remove, collapse = "|")),
    colors = str_remove_all(colors, paste(remove, collapse = "|")),
    colors = strsplit(colors, ","),
    color_hex = strsplit(color_hex, ",")
  ) %>%
  unnest(c(colors, color_hex)) %>%
  mutate(color_hex = str_trim(color_hex)) %>%
  mutate(colors = str_trim(colors)) %>%
  distinct()

view(colorSelect)

```

```{r EDA}
# We only care about if the colors are in the paintings or not

presentColors <- bob_ross %>%
  gather(color, present,-c(1:10)) %>%
  filter(present == 1) %>%
  mutate(color = str_to_title(str_replace(color, "_", " ")))

bob_ross <-
  merge(x = presentColors,
        y = colorSelect,
        by.y = "colors",
        by.x = "color") %>%
  select(-c(2, 4, 8:12))

view(bob_ross)
```

```{r EDA}
# Looking at total count of colors used

bob_ross %>%
  count(color, color_hex.y, sort = TRUE) %>%
  mutate(color = fct_reorder(color, n)) %>%
  ggplot(aes(color, n, fill = I(color_hex.y))) +
  geom_col() +
  coord_flip()

```

```{r EDA}
# Percentage of titanium white used over seasons

bob_ross %>%
  add_count(season, name = "totalColors") %>%
  count(season, color, totalColors,  sort = TRUE) %>%
  mutate(percentage = n / totalColors) %>%
  filter(color == "Titanium White") %>%
  ggplot(aes(season, percentage)) +
  geom_line() 
  
```

```{r EDA}
# Going to look into common words in title, so we need to merge before that
bob_ross <-
  merge(x = bob_ross, y = BrokenTitle, by = "painting_title")

```

```{r EDA}
# Usage of a few words in titles over seasons by paint color
bob_ross %>%
  group_by(NewTitle, season, color) %>%
  filter(NewTitle == "mountain" |
           NewTitle == "winter" | NewTitle == "day") %>%
  ggplot(aes(season, fill = I(color_hex.y))) +
  geom_bar(stat = "count") +
  facet_wrap( ~ NewTitle)
```

