---
title: "main"
output: html_document
date: "2023-08-08"
---

#Today's Link: https://github.com/rfordatascience/tidytuesday/blob/master/data/2023/2023-07-25/readme.md

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
suppressMessages(library(tidyverse))
suppressMessages(library(skimr))
suppressMessages(library(plotly))
```

```{r EDA}
#Load in the data
scurvy <-
  readr::read_csv(
    'https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2023/2023-07-25/scurvy.csv'
  )

#The data is too small to draw any meaningful conclusions, but lets look anyways
skim(scurvy)
```

```{r EDA}
#Separate the numerical component of severity

scurvy <- scurvy %>%
  pivot_longer(4:7, names_to = "symptom", values_to = "severity") %>%
  separate(severity,
           sep = "_",
           into = c("NumSev", "DescSev")) %>%
  separate_wider_delim(symptom, delim = "_d6", names = c("symptom", NA)) 

```

```{r EDA}
#Lets look at the frequency of treatments and the severity of the case

G1 <- scurvy %>%
  ggplot(mapping = aes(x = treatment, fill = NumSev)) +
  coord_flip() +
  geom_bar(alpha = 0.7) +
  facet_wrap(~fit_for_duty_d6)

ggplotly(G1)
```

```{r EDA}
#Lets take a look at the symptom and severity this time

G1 <- scurvy %>%
  ggplot(mapping = aes(x = symptom, fill = NumSev)) +
  coord_flip() +
  geom_bar(alpha = 0.7) +
  facet_wrap(~fit_for_duty_d6)

ggplotly(G1)
```

