---
title: "main"
output: html_document
date: "2023-07-16"
---

#Today's Link: https://github.com/rfordatascience/tidytuesday/tree/master/data/2023/2023-03-28

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
suppressMessages(library(tidyverse))
suppressMessages(library(skimr))
```

```{r EDA}
# Load in the data and merge it together for later
transitions <-
  readr::read_csv(
    'https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2023/2023-03-28/transitions.csv'
  ) %>%
  mutate(begin = as_datetime(begin), end = as_datetime(end))

timezones <-
  readr::read_csv(
    'https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2023/2023-03-28/timezones.csv'
  ) %>%
  select(-c("comments"))
timezone_countries <-
  readr::read_csv(
    'https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2023/2023-03-28/timezone_countries.csv'
  )
countries <-
  readr::read_csv(
    'https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2023/2023-03-28/countries.csv'
  )

CDF <-
  merge(x = countries, y = timezone_countries, on = "country_code")

CDF <- merge(x = CDF, y = timezones, on = "zone")

CDF <- merge(x = CDF, y = transitions, on = "zone") %>%
  drop_na() 

skim(CDF)
```

```{r EDA}
# Lets take a look at how many time zones are in each country

CDF %>%
  count(place_name) %>%
  mutate(place_name = fct_reorder(place_name, n)) %>%
  filter(n > 500) %>%
  ggplot(mapping = aes(x = place_name, y = n, fill = place_name)) +
  geom_col() +
  coord_flip() +
  theme(legend.position = "none")

```


```{r EDA}
# Now lets take a look at which countries use day light savings

world <- map_data("world")

G <-
  ggplot() +
  geom_map(
    data = world,
    map = world,
    mapping = aes(x = long, y = lat, map_id = region),
    color = "black",
    fill = "lightgray"
  ) +
  xlab("location_long") +
  ylab("location_lat") +
  geom_point(
    data = CDF,
    mapping = aes(x = longitude,
                  y = latitude,
                  color = dst),
    alpha = 0.7
  ) 

G
```
```{r EDA}
#timezone offset from UTC
G2 <-
  ggplot() +
  geom_map(
    data = world,
    map = world,
    mapping = aes(x = long, y = lat, map_id = region),
    color = "black",
    fill = "lightgray"
  ) +
  xlab("location_long") +
  ylab("location_lat") +
  geom_point(
    data = CDF,
    mapping = aes(x = longitude,
                  y = latitude,
                  color = offset),
    alpha = 0.7
  ) +
  scale_color_gradientn(colors = rainbow(10))


G2
```


